site_name: SciGuides
theme: 
  name: material
  custom_dir: overrides
  logo: images/logo.png
  favicon: images/logo.png
  palette:
    scheme: slate
    primary: yellow
    accent: amber
  font:
    text: Roboto
    code: Roboto mono
  features:
    - navigation.footer
  footer: ""

nav:
  - Home: index.md
  - Concepts: 
    - About: ./concepts/README.md
    - Intro to Software: ./concepts/IntroToSoftware.md
    - Setting up Software: ./concepts/SoftwareSetup.md
    - Objects and Classes: ./concepts/ObjectsAndClasses.md
    - Making and Managing Data: ./concepts/MakingAndManagingData.md