site_name: SciGuides
theme: 
  name: material
  custom_dir: overrides
  logo: images/logo.png
  favicon: images/logo.png
  palette:
    scheme: slate
    primary: yellow
    accent: amber
  font:
    text: Roboto
    code: Roboto mono
  features:
    - navigation.footer
  footer: ""

nav:
  - Home: index.md
  - Lessons: 
    - About: ./lessons/README.md
    - Intro to Software: ./lessons/IntroToSoftware.md
    - Setting up Software: ./lessons/SoftwareSetup.md
    - Intro to Java: ./lessons/IntroToJava.md
    - Intro to Java 2: ./lessons/IntroToJava2.md
  - Projects: 
    - About: ./projects/README.md
    - Intro To Programming: 
      - About: ./projects/intro-to-programming/README.md
      - Programming 101: ./projects/intro-to-programming/Programming101.md
      - Java 101: ./projects/intro-to-programming/Java101.md
      - Java 102: ./projects/intro-to-programming/Java102.md
    - Basic Subsystems: 
      - About: ./projects/basic-subsystems/README.md
      - General Subsystem Structure: ./projects/basic-subsystems/GeneralSubsystemStructure.md
      - Differential Drive: ./projects/basic-subsystems/DifferentialDrive.md
      - Simple Shooter: ./projects/basic-subsystems/SimpleShooter.md
  - Reference Sheets: 
    - About: ./sheets/README.md
    - Advanced Java: ./sheets/AdvancedJava.md
    - Command Based Programming: ./sheets/CommandBased.md
    - Command Line Navigation: ./sheets/CommandLineNavigation.md
    - Control Theory: ./sheets/ControlTheory.md
    - Environment Setup: ./sheets/EnvironmentSetup.md
    - File Structure: ./sheets/FileStructure.md
    - Git Guide: ./sheets/GitGuide.md
    - Sensors: ./sheets/Sensors.md
    - Simulation: ./sheets/Simulation.md
    - Telemetry: ./sheets/Telemetry.md
    - Trig Guide: ./sheets/Trigonometry.md